export const ALL_ARCANA_CARDS = {
  WA: {
    symbol: "AW",
    name: "Ace of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  W2: {
    symbol: "2W",
    name: "Two of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  W3: {
    symbol: "3W",
    name: "Three of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  W4: {
    symbol: "4W",
    name: "Four of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  W5: {
    symbol: "5W",
    name: "Five of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  W6: {
    symbol: "6W",
    name: "Six of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  W7: {
    symbol: "7W",
    name: "Seven of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  W8: {
    symbol: "8W",
    name: "Eight of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  W9: {
    symbol: "9W",
    name: "Nine of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  W10: {
    symbol: "10W",
    name: "Ten of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  WP: {
    symbol: "PW",
    name: "Page of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  WKN: {
    symbol: "KNW",
    name: "Knight of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  WQ: {
    symbol: "QW",
    name: "Queen of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  WK: {
    symbol: "KW",
    name: "King of Wands",
    arcana: "minor",
    class: "wands",
    keywords: "",
  },
  SA: {
    symbol: "AS",
    name: "Ace of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  S2: {
    symbol: "2S",
    name: "Two of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  S3: {
    symbol: "3S",
    name: "Three of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  S4: {
    symbol: "4S",
    name: "Four of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  S5: {
    symbol: "5S",
    name: "Five of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  S6: {
    symbol: "6S",
    name: "Six of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  S7: {
    symbol: "7S",
    name: "Seven of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  S8: {
    symbol: "8S",
    name: "Eight of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  S9: {
    symbol: "9S",
    name: "Nine of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  S10: {
    symbol: "10S",
    name: "Ten of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  SP: {
    symbol: "PS",
    name: "Page of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  SKN: {
    symbol: "KNS",
    name: "Knight of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  SQ: {
    symbol: "QS",
    name: "Queen of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  SK: {
    symbol: "KS",
    name: "King of Swords",
    arcana: "minor",
    class: "swords",
    keywords: "",
  },
  PA: {
    symbol: "AP",
    name: "Ace of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  P2: {
    symbol: "2P",
    name: "Two of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  P3: {
    symbol: "3P",
    name: "Three of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  P4: {
    symbol: "4P",
    name: "Four of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  P5: {
    symbol: "5P",
    name: "Five of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  P6: {
    symbol: "6P",
    name: "Six of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  P7: {
    symbol: "7P",
    name: "Seven of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  P8: {
    symbol: "8P",
    name: "Eight of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  P9: {
    symbol: "9P",
    name: "Nine of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  P10: {
    symbol: "10P",
    name: "Ten of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  PP: {
    symbol: "PP",
    name: "Page of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  PKN: {
    symbol: "KNP",
    name: "Knight of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  PQ: {
    symbol: "QP",
    name: "Queen of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  PK: {
    symbol: "KP",
    name: "King of Pentacles",
    arcana: "minor",
    class: "pentacles",
    keywords: "",
  },
  CA: {
    symbol: "AC",
    name: "Ace of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  C2: {
    symbol: "2C",
    name: "Two of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  C3: {
    symbol: "3C",
    name: "Three of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  C4: {
    symbol: "4C",
    name: "Four of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  C5: {
    symbol: "5C",
    name: "Five of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  C6: {
    symbol: "6C",
    name: "Six of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  C7: {
    symbol: "7C",
    name: "Seven of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  C8: {
    symbol: "8C",
    name: "Eight of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  C9: {
    symbol: "9C",
    name: "Nine of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  C10: {
    symbol: "10C",
    name: "Ten of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  CP: {
    symbol: "PC",
    name: "Page of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  CKN: {
    symbol: "KNC",
    name: "Knight of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  CQ: {
    symbol: "QC",
    name: "Queen of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  CK: {
    symbol: "KC",
    name: "King of Cups",
    arcana: "minor",
    class: "cups",
    keywords: "",
  },
  F: {
    symbol: "F",
    name: "The Fool",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  MAG: {
    symbol: "MAG",
    name: "The Magician",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  HP: {
    symbol: "HP",
    name: "The High Priestess",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  EF: {
    symbol: "EF",
    name: "The Empress",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  EM: {
    symbol: "EM",
    name: "The Emperor",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  HEI: {
    symbol: "HEI",
    name: "The Heirophant",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  LOV: {
    symbol: "LOV",
    name: "The Lovers",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  CH: {
    symbol: "CH",
    name: "The Chariot",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  JUS: {
    symbol: "JUS",
    name: "Justice",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  HER: {
    symbol: "HER",
    name: "The Hermit",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  WF: {
    symbol: "WF",
    name: "The Wheel of Fortune",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  STR: {
    symbol: "STR",
    name: "Strength",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  HM: {
    symbol: "HM",
    name: "The Hanged Man",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  DEA: {
    symbol: "DEA",
    name: "Death",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  TEM: {
    symbol: "TEM",
    name: "Temperance",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  DEV: {
    symbol: "DEV",
    name: "The Devil",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  TOW: {
    symbol: "TOW",
    name: "The Tower",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  ST: {
    symbol: "ST",
    name: "The Star",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  MO: {
    symbol: "MO",
    name: "The Moon",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  SUN: {
    symbol: "SUN",
    name: "The Sun",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  JUD: {
    symbol: "JUD",
    name: "Judgement",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
  WOR: {
    symbol: "WOR",
    name: "The World",
    arcana: "major",
    class: "trump",
    keywords: "",
  },
};

export const CARD_LIST = [
  { symbol: "WA", upright: true },
  { symbol: "W2", upright: true },
  { symbol: "W3", upright: true },
  { symbol: "W4", upright: true },
  { symbol: "W5", upright: true },
  { symbol: "W6", upright: true },
  { symbol: "W7", upright: true },
  { symbol: "W8", upright: true },
  { symbol: "W9", upright: true },
  { symbol: "W10", upright: true },
  { symbol: "WP", upright: true },
  { symbol: "WKN", upright: true },
  { symbol: "WQ", upright: true },
  { symbol: "WK", upright: true },
  { symbol: "SA", upright: true },
  { symbol: "S2", upright: true },
  { symbol: "S3", upright: true },
  { symbol: "S4", upright: true },
  { symbol: "S5", upright: true },
  { symbol: "S6", upright: true },
  { symbol: "S6", upright: true },
  { symbol: "S7", upright: true },
  { symbol: "S8", upright: true },
  { symbol: "S9", upright: true },
  { symbol: "S10", upright: true },
  { symbol: "SP", upright: true },
  { symbol: "SKN", upright: true },
  { symbol: "SQ", upright: true },
  { symbol: "SK", upright: true },
  { symbol: "PA", upright: true },
  { symbol: "P2", upright: true },
  { symbol: "P3", upright: true },
  { symbol: "P4", upright: true },
  { symbol: "P5", upright: true },
  { symbol: "P6", upright: true },
  { symbol: "P7", upright: true },
  { symbol: "P8", upright: true },
  { symbol: "P9", upright: true },
  { symbol: "P10", upright: true },
  { symbol: "PP", upright: true },
  { symbol: "PKN", upright: true },
  { symbol: "PQ", upright: true },
  { symbol: "PK", upright: true },
  { symbol: "CA", upright: true },
  { symbol: "C2", upright: true },
  { symbol: "C3", upright: true },
  { symbol: "C4", upright: true },
  { symbol: "C5", upright: true },
  { symbol: "C6", upright: true },
  { symbol: "C7", upright: true },
  { symbol: "C8", upright: true },
  { symbol: "C9", upright: true },
  { symbol: "C10", upright: true },
  { symbol: "CP", upright: true },
  { symbol: "CKN", upright: true },
  { symbol: "CQ", upright: true },
  { symbol: "CK", upright: true },
  { symbol: "F", upright: true },
  { symbol: "MAG", upright: true },
  { symbol: "HP", upright: true },
  { symbol: "EF", upright: true },
  { symbol: "EM", upright: true },
  { symbol: "HEI", upright: true },
  { symbol: "LOV", upright: true },
  { symbol: "CH", upright: true },
  { symbol: "JUS", upright: true },
  { symbol: "HER", upright: true },
  { symbol: "WF", upright: true },
  { symbol: "STR", upright: true },
  { symbol: "HM", upright: true },
  { symbol: "DEA", upright: true },
  { symbol: "TEM", upright: true },
  { symbol: "DEV", upright: true },
  { symbol: "TOW", upright: true },
  { symbol: "ST", upright: true },
  { symbol: "MO", upright: true },
  { symbol: "SUN", upright: true },
  { symbol: "JUD", upright: true },
  { symbol: "WOR", upright: true },
];

export const MINOR_ARCANA = {
  wands: { class: "artisans", faculty: "creativity and will", element: "fire" },
  swords: {
    class: "nobility and military",
    faculty: "reason, wisdom, and intellect",
    element: "air",
  },
  pentacles: {
    class: "merchants",
    faculty: "possessions",
    element: "earth",
  },
  cups: {
    class: "clergy",
    faculty: "emotions and love",
    element: "water",
  },
};
